# Generated by Django 5.2.3 on 2025-06-16 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashflow", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashflowrecord",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 6, 16, 22, 43, 54, 828976, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата",
            ),
        ),
    ]
