# Generated by Django 5.2.3 on 2025-06-16 22:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashflow", "0002_alter_cashflowrecord_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashflowrecord",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Дата"
            ),
        ),
    ]
