# Generated by Django 5.2.3 on 2025-06-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashflow", "0003_alter_cashflowrecord_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashflowrecord",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Комментарий"),
        ),
    ]
