# Generated by Django 5.2.3 on 2025-06-16 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashflow", "0004_alter_cashflowrecord_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashflowrecord",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cashflow.subcategory",
                verbose_name="Подкатегория",
            ),
        ),
    ]
